---

- name: Create {{ prometheus_root_dir }} directory
  become: yes
  file:
    name: "{{ prometheus_root_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Create {{ prometheus_dist_dir }} directory
  become: yes
  file:
    name: "{{ prometheus_dist_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create {{ prometheus_bin_dir }}/bin directory
  become: yes
  file:
    name: "{{ prometheus_bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create {{ kafka_exporter_init_dir }}/bin directory
  become: yes
  file:
    name: "{{ kafka_exporter_init_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
